additionalArguments: []
service:
  type: LoadBalancer

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    namespaces:
      - "traefik-ns"