apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blitzshare-api-crd
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/api`)
      middlewares:
        - name: strip-api-prefix
      services:
        - kind: Service
          name: blitzshare-api-svc
          port: 80
    - kind: Rule
      match: PathPrefix(`/`)
      middlewares:
        - name: strip-api-prefix
      services:
        - kind: Service
          name: blitzshare-bootstrap-svc
          port: 63785
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
spec:
  stripPrefix:
    prefixes:
      - /api
      - /p2p
    forceSlash: false